pool:
  demands: 
    - msbuild
    - visualstudio
    - vstest

variables:
  Solution: "$(Build.SourcesDirectory)/Activities/Community.Activities.sln"
  BuildConfiguration: "Release"
  BuildPlatform: "Any CPU"

trigger:
  branches:
    include:
      - develop
      - master

pr:
  branches:
    include:
      - develop
      - master

stages:
  - stage: 'CI'
    displayName: 'CI'
    jobs:
      - job: 'Build'
        displayName: 'Build'
        pool:
          vmImage: 'windows-latest'
        steps:
          - template: .build.steps.yml
            parameters:
              solution: '$(Solution)'
              buildPlatform: '$(BuildPlatform)'
              buildConfiguration: '$(BuildConfiguration)'

  - stage: 'PublishToDevFTPPackage'
    displayName: 'Publish FTP Package (DEV)'
    dependsOn: CI
    condition: eq(variables['FTP'], true)
    jobs:
      - deployment: 'PublishFTPToDev'
        displayName: 'Publish FTP to (DEV)'
        pool:
          vmImage: windows-latest
        environment: 'DEV'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: .release.steps.yml
                  parameters:
                    nugetFeed: 'UiPath-Internal'
                    PackagesToDeploy: '$(ArtifactsDirectory)/*.FTP.*.nupkg;!$(ArtifactsDirectory)/*.FTP.*.symbols.nupkg'
                    packageName: 'UiPath.FTP.Activities'
