trigger:
  branches:
    include:
      - master
      - develop
      - release/*
      - support/*
  paths:
    include:
      - Activities/Credentials/*
      - Activities/Activities.Credentials.sln

variables:
  majorVersion: '1'
  minorVersion: '3'
  revision: $[counter(variables['minorVersion'], 1)] #this will get reset when minor gets bumped.
  packageVersion: '$(majorVersion).$(minorVersion).$(revision)'

pr:
  branches:
    include:
      - master
      - develop
      - release/*
      - support/*
      - feature/*
  paths:
    include:
      - Activities/Credentials/*
      - Activities/Activities.Credentials.sln

jobs:
  - template: "../.pipelines/jobs/ci.yml"
    parameters:
      BuildProject: "../Activities.Credentials.sln"
      BuildConfiguration: "Release"
      BuildPlatform: "AnyCPU"
      rootPath: $(Build.SourcesDirectory)\Activities\Credentials\
      packagesDirectory: $(Build.SourcesDirectory)\Activities\packages\
      versionReference: "UiPath.Credentials.Activities/Properties/AssemblyInfo.cs"
      versionNumber: ${{ variables.packageVersion }}
