trigger:
  branches:
    include:
      - master
      - develop
      - release/*
      - support/*
  paths:
    include:
      - Activities/Python/*
      - Activities/Activities.Python.sln

variables:
  majorVersion: '1'
  minorVersion: '2'
  revision: $[counter(variables['minorVersion'], 1)] #this will get reset when minor gets bumped.
  packageVersion: '$(majorVersion).$(minorVersion).$(revision)'

pr:
  branches:
    include:
      - master
      - develop
      - release/*
      - support/*
      - feature/*
  paths:
    include:
      - Activities/Python/*
      - Activities/Activities.Python.sln

jobs:
  - template: "../.pipelines/jobs/ci.yml"
    parameters:
      BuildProject: "../Activities.Python.sln"
      BuildConfiguration: "Release"
      BuildPlatform: "AnyCPU"
      rootPath: $(Build.SourcesDirectory)\Activities\Python\
      packagesDirectory: $(Build.SourcesDirectory)\Activities\packages\
      restoreDependencies: 
        - "UiPath.Python/UiPath.Python.csproj"
        - "UiPath.Python.Activitiess/UiPath.Python.Activities.csproj"
      testList: 
        - "UiPath.Python.Tests/UiPath.Python.Tests.csproj"
      versionReference: "PythonPackageVersion.cs"
      versionNumber: ${{ variables.packageVersion }}
